### ISSUE TITLE
[작업] SQL 작성 및 트랜잭션 설계

### ISSUE THREAD

**Issue by Vactor0911** [Vactor0911/task-ez#11]
**개요**
사용자의 데이터를 읽고 쓰기 위한 SQL 문을 작성하고, 트랜잭션을 설계한다.

**진행해야 할 업무**
- **SQL문 작성**
  - [x] 회원가입 시 사용자 정보 삽입
    - 아이디, 비밀번호, 별명 삽입
  - [x] 로그인 시 사용자 정보 검증
    - 아이디, 비밀번호가 일치하는 행 검색 
  - [x] 사용자가 생성한 작업 전체 불러오기
    - 작업 테이블에서 사용자ID가 일치하는 행 검색
  - [x] 특정 작업 불러오기
    - 사용자 ID와 작업ID가 주어진 값과 일치하는 작업 검색
  - [x] 새로운 작업 생성
    - 사용자 ID, 제목, 내용, 시작일, 종료일, 색상 삽입
  - [x] 기존 작업 편집
    - 작업ID가 일치하는 작업에 대하여 제목, 내용, 시작일, 종료일, 색상 변경
  - [x] 작업 삭제
    - 작업 ID가 일치하는 작업에 대하여 행 삭제
  - [x] 종료일 임박 작업 불러오기
    - 사용자 ID가 일치하는 작업 중 현재 날짜 기준 종료일이 3일 이하로 남은 작업 검색
  - [x] 작업 제목 검색
    - 작업의 제목이 일치하는 행 검색 (단, 입력된 문자열로 시작하는 제목을 가진 작업임.)

- **트랜잭션 설계**
  - MariaDB 트랜잭션 설계

**Comment by shkim429** [comment]
-  회원가입 시 사용자 정보 삽입
   ```sql
   INSERT INTO `user` (`id`, `password`, `name`) VALUES ('qwer', 'qwer1234', '큐');
   ```

**Comment by shkim429** [comment]
- 로그인 시 사용자 정보 검증
  ```sql
  SELECT * FROM `user` 
  WHERE `id` = 'ttt' AND `password` = 'test0000';
  ```

**Comment by shkim429** [comment]
- 사용자가 생성한 작업 전체 불러오기
   ```sql
   SELECT * FROM `task`
   WHERE `user_id` = 1;
   ```

**Comment by shkim429** [comment]
- 특정 작업 불러오기
   ```sql
   SELECT * from `task`
   WHERE `user_id` = 1 AND `task_id` = 1;
   ```

**Comment by shkim429** [comment]
-  새로운 작업 생성
   ```sql
   INSERT INTO `task` (`user_id`, `title`, `content`, `start_date`, `end_date`, `color`) VALUES (1, '본가', '18시 시외버스', '2024-12-20','2024-12-20','ad3927');
   ```

**Comment by shkim429** [comment]
- 기존 작업 편집
   ```sql
   UPDATE task
   SET `title` = '집가기', `content` = '09시 대전역', `start_date` = '2024-12-30', `end_date` = '2024-12-30', 
   `color` = '#ad3927'
   WHERE `task_id` = 4;
   ```

**Comment by shkim429** [comment]
- 작업 삭제
   ```sql
   DELETE FROM `task`
   WHERE `task_id` = 4;
   ```

**Comment by shkim429** [comment]
- 작업 제목 검색
   ```sql
   SELECT * FROM `task`
   WHERE `title` LIKE '%집%' AND `user_id` = 1;
   ```

**Comment by shkim429** [comment]
- 종료일 임박 작업 불러오기
   ```sql
   SELECT * FROM `task` 
   WHERE  `user_id` = 1 AND DATEDIFF(end_date, NOW()) <= 3
   ORDER BY `end_date` ASC;
   ```
