### ISSUE TITLE
[작업] 백엔드 서버 API 개발

### ISSUE THREAD

**Issue by Vactor0911** [Vactor0911/task-ez#12]
**개요**
웹 클라이언트에서 요청하는 데이터를 처리할 수 있도록 API를 개발한다.

**진행해야 할 업무**
- [x] cors 설정
- [x] MariaDB 연결
- [x] MariaDB와 SQL문을 이용하여 데이터 핸들링 및 클라이언트 요청 처리
- [x] 웹 통신을 받고 처리할 API 개발
  - [x] 회원가입
  - [x] 로그인
  - [x] 로그아웃
  - [x] 사용자가 등록한 작업 목록 전송
  - [x] 특정 작업 정보 전송
  - [x] 새 작업 생성
  - [x] 기존 작업 편집
  - [x] 작업 삭제
  - [x] 작업 완료
  - [x] 종료일 임박 작업 목록 전송
  - [x] 작업 제목 검색 결과 전송

**Comment by Vactor0911** [comment]
@L-Hits  통신을 위해 각 API 별 입력 데이터와 반환 데이터의 형식 및 구조 정보가 필요함

**Comment by L-Hits** [comment]
# 새 작업 생성 및 기존 작업 편집 시 
## input :
![image](https://github.com/user-attachments/assets/82ac05c6-4f68-4e83-b593-0981d29cf72f)

## output :
![image](https://github.com/user-attachments/assets/c26d6d9a-e859-4385-80c9-980b715dab91)

### date 도 문자열 형식입니다.

**Comment by L-Hits** [comment]
### 작업 삭제 API 구현 완료

**작업 개요**:
- 사용자가 `task_id`와 `user_id`를 제공하면, 작업의 `deleted` 필드를 1로 업데이트하여 논리적으로 삭제 처리합니다.
- 삭제된 작업의 데이터를 반환합니다.

**주요 로직**:
1. `task_id`와 `user_id` 유효성 검증
2. `deleted` 값 업데이트 쿼리 실행
3. 삭제된 작업 데이터 조회 및 반환
4. 예외 처리 (삭제 대상 없음, 서버 오류)

**테스트 결과**:
#### Input:
```json
{
  "task_id": 7,
  "user_id": 2
}
```

#### Output:
```json
{
  "success": true,
  "message": "작업이 성공적으로 삭제되었습니다.",
  "task": {
    "task_id": 7,
    "user_id": 2,
    "title": "변경된 작업",
    "content": "작업이 변경되었습니다.",
    "start_date": "2024-12-15T15:00:00.000Z",
    "end_date": "2024-12-16T15:00:00.000Z",
    "color": "#FCD997",
    "finished": 0,
    "deleted": 1
  }
}
```
