### ISSUE TITLE
[작업] 로그인, 회원가입 모달창 수정

### ISSUE THREAD

**Issue by L-Hits** [Vactor0911/task-ez#23]
**개요**
로그인, 회원가입 모달창에 수정이 필요합니다.

**진행해야 할 업무**
- [ ] 로그인 모달창에 패스워드 숨김여부 추가
- [ ] 로그인 모달창에 이메일 -> 아이디 로 변경
- [ ] 회원가입 모달창에 패스워드 숨김여부 추가
- [ ] 회원가입 모달창에 이메일 -> 아이디 로 변경

**Comment by Vactor0911** [comment]
코드 리팩토링 과정에서 위 작업을 함께 처리했음.
#31 이슈 참고
